# Generated by Django 5.2.5 on 2025-08-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('creditos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('LAVADORA', 'Lavadora'), ('SECADORA', 'Secadora')], max_length=10)),
                ('ip_tomada', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=100)),
                ('local_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='laundry.inquilino')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='laundry.maquina')),
            ],
        ),
    ]
