# Generated by Django 5.2.5 on 2025-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicouso',
            old_name='data_hora',
            new_name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='historicouso',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
