# Generated by Django 5.2.5 on 2025-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_rename_data_hora_historicouso_data_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tempo_ciclo_minutos',
            field=models.PositiveIntegerField(default=70, help_text='Tempo de duração do ciclo em minutos. Este valor será usado para programar o timer do dispositivo Tasmota.'),
        ),
    ]
