# Generated by Django 6.0 on 2025-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_sync_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponivel'), ('Em Uso', 'Em Uso'), ('Manutenção', 'Manutencao')], default='Disponível', max_length=20),
        ),
    ]
